const i18Obj = {
  'en': {
    'skills': 'Skills',
    'portfolio': 'Portfolio',
    'video': 'Video',
    'price': 'Price',
    'contacts': 'Contacts',
    'hero-title': 'Alexa Rise',
    'hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
    'hire': 'Hire me',
    'skill-title1': 'Digital photography',
    'skill-text1': 'High-quality photos in the studio and on the nature',
    'skill-title2': 'Video shooting',
    'skill-text2': 'Capture your moments so that they always stay with you',
    'skill-title3': 'Rotouch',
    'skill-text3': 'I strive to make photography surpass reality',
    'skill-title4': 'Audio',
    'skill-text4': 'Professional sounds recording for video, advertising, portfolio',
    'winter': 'Winter',
    'spring': 'Spring',
    'summer': 'Summer',
    'autumn': 'Autumn',
    'price-description11': 'One location',
    'price-description12': '120 photos in color',
    'price-description13': '12 photos in retouch',
    'price-description14': 'Readiness 2-3 weeks',
    'price-description15': 'Make up, visage',
    'price-description21': 'One or two locations',
    'price-description22': '200 photos in color',
    'price-description23': '20 photos in retouch',
    'price-description24': 'Readiness 1-2 weeks',
    'price-description25': 'Make up, visage',
    'price-description31': 'Three locations or more',
    'price-description32': '300 photos in color',
    'price-description33': '50 photos in retouch',
    'price-description34': 'Readiness 1 week',
    'price-description35': 'Make up, visage, hairstyle',
    'order': 'Order shooting',
    'contact-me': 'Contact me',
	  'placeholder-email': 'E-mail',
    'placeholder-phone': 'Phone',
    'placeholder-message': 'Message',
    'send-message': 'Send message'
  },
  'ru': {
    'skills': 'Навыки',
    'portfolio': 'Портфолио',
    'video': 'Видео',
    'price': 'Цены',
    'contacts': 'Контакты',
    'hero-title': 'Алекса Райс',
    'hero-text': 'Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом',
    'hire': 'Пригласить',
    'skill-title1': 'Фотография',
    'skill-text1': 'Высококачественные фото в студии и на природе',
    'skill-title2': 'Видеосъемка',
    'skill-text2': 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
    'skill-title3': 'Ретушь',
    'skill-text3': 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
    'skill-title4': 'Звук',
    'skill-text4': 'Профессиональная запись звука для видео, рекламы, портфолио',
    'winter': 'Зима',
    'spring': 'Весна',
    'summer': 'Лето',
    'autumn': 'Осень',
    'price-description11': 'Одна локация',
    'price-description12': '120 цветных фото',
    'price-description13': '12 отретушированных фото',
    'price-description14': 'Готовность через 2-3 недели',
    'price-description15': 'Макияж, визаж',
    'price-description21': 'Одна-две локации',
    'price-description22': '200 цветных фото',
    'price-description23': '20 отретушированных фото',
    'price-description24': 'Готовность через 1-2 недели',
    'price-description25': 'Макияж, визаж',
    'price-description31': 'Три локации и больше',
    'price-description32': '300 цветных фото',
    'price-description33': '50 отретушированных фото',
    'price-description34': 'Готовность через 1 неделю',
    'price-description35': 'Макияж, визаж, прическа',
    'order': 'Заказать съемку',
    'contact-me': 'Свяжитесь со мной',
	  'placeholder-email': 'Почта',
    'placeholder-phone': 'Телефон',
    'placeholder-message': 'Сообщение',
    'send-message': 'Отправить'
  }
}
export default i18Obj;
